name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build & Push to Docker Hub (GitHub runner)
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/user8970/seikaAI
            git reset --hard
            git pull origin main
          
            docker compose build
            docker compose up -d --remove-orphans
